# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from shared.proto import auth_service_pb2 as shared_dot_proto_dot_auth__service__pb2


class AuthServiceStub(object):
    """Authentication Service Definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterUser = channel.unary_unary(
                '/omnipricex.auth.AuthService/RegisterUser',
                request_serializer=shared_dot_proto_dot_auth__service__pb2.RegisterUserRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_auth__service__pb2.UserResponse.FromString,
                )
        self.LoginUser = channel.unary_unary(
                '/omnipricex.auth.AuthService/LoginUser',
                request_serializer=shared_dot_proto_dot_auth__service__pb2.LoginUserRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_auth__service__pb2.LoginUserResponse.FromString,
                )
        self.VerifyToken = channel.unary_unary(
                '/omnipricex.auth.AuthService/VerifyToken',
                request_serializer=shared_dot_proto_dot_auth__service__pb2.VerifyTokenRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_auth__service__pb2.VerifyTokenResponse.FromString,
                )
        self.RefreshToken = channel.unary_unary(
                '/omnipricex.auth.AuthService/RefreshToken',
                request_serializer=shared_dot_proto_dot_auth__service__pb2.RefreshTokenRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_auth__service__pb2.LoginUserResponse.FromString,
                )
        self.LogoutUser = channel.unary_unary(
                '/omnipricex.auth.AuthService/LogoutUser',
                request_serializer=shared_dot_proto_dot_auth__service__pb2.LogoutUserRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetUserProfile = channel.unary_unary(
                '/omnipricex.auth.AuthService/GetUserProfile',
                request_serializer=shared_dot_proto_dot_auth__service__pb2.GetUserProfileRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_auth__service__pb2.UserResponse.FromString,
                )
        self.UpdateUserProfile = channel.unary_unary(
                '/omnipricex.auth.AuthService/UpdateUserProfile',
                request_serializer=shared_dot_proto_dot_auth__service__pb2.UpdateUserProfileRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_auth__service__pb2.UserResponse.FromString,
                )


class AuthServiceServicer(object):
    """Authentication Service Definition
    """

    def RegisterUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoginUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LogoutUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUserProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterUser,
                    request_deserializer=shared_dot_proto_dot_auth__service__pb2.RegisterUserRequest.FromString,
                    response_serializer=shared_dot_proto_dot_auth__service__pb2.UserResponse.SerializeToString,
            ),
            'LoginUser': grpc.unary_unary_rpc_method_handler(
                    servicer.LoginUser,
                    request_deserializer=shared_dot_proto_dot_auth__service__pb2.LoginUserRequest.FromString,
                    response_serializer=shared_dot_proto_dot_auth__service__pb2.LoginUserResponse.SerializeToString,
            ),
            'VerifyToken': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyToken,
                    request_deserializer=shared_dot_proto_dot_auth__service__pb2.VerifyTokenRequest.FromString,
                    response_serializer=shared_dot_proto_dot_auth__service__pb2.VerifyTokenResponse.SerializeToString,
            ),
            'RefreshToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshToken,
                    request_deserializer=shared_dot_proto_dot_auth__service__pb2.RefreshTokenRequest.FromString,
                    response_serializer=shared_dot_proto_dot_auth__service__pb2.LoginUserResponse.SerializeToString,
            ),
            'LogoutUser': grpc.unary_unary_rpc_method_handler(
                    servicer.LogoutUser,
                    request_deserializer=shared_dot_proto_dot_auth__service__pb2.LogoutUserRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetUserProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserProfile,
                    request_deserializer=shared_dot_proto_dot_auth__service__pb2.GetUserProfileRequest.FromString,
                    response_serializer=shared_dot_proto_dot_auth__service__pb2.UserResponse.SerializeToString,
            ),
            'UpdateUserProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserProfile,
                    request_deserializer=shared_dot_proto_dot_auth__service__pb2.UpdateUserProfileRequest.FromString,
                    response_serializer=shared_dot_proto_dot_auth__service__pb2.UserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'omnipricex.auth.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Authentication Service Definition
    """

    @staticmethod
    def RegisterUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/omnipricex.auth.AuthService/RegisterUser',
            shared_dot_proto_dot_auth__service__pb2.RegisterUserRequest.SerializeToString,
            shared_dot_proto_dot_auth__service__pb2.UserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LoginUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/omnipricex.auth.AuthService/LoginUser',
            shared_dot_proto_dot_auth__service__pb2.LoginUserRequest.SerializeToString,
            shared_dot_proto_dot_auth__service__pb2.LoginUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VerifyToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/omnipricex.auth.AuthService/VerifyToken',
            shared_dot_proto_dot_auth__service__pb2.VerifyTokenRequest.SerializeToString,
            shared_dot_proto_dot_auth__service__pb2.VerifyTokenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RefreshToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/omnipricex.auth.AuthService/RefreshToken',
            shared_dot_proto_dot_auth__service__pb2.RefreshTokenRequest.SerializeToString,
            shared_dot_proto_dot_auth__service__pb2.LoginUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LogoutUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/omnipricex.auth.AuthService/LogoutUser',
            shared_dot_proto_dot_auth__service__pb2.LogoutUserRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/omnipricex.auth.AuthService/GetUserProfile',
            shared_dot_proto_dot_auth__service__pb2.GetUserProfileRequest.SerializeToString,
            shared_dot_proto_dot_auth__service__pb2.UserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateUserProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/omnipricex.auth.AuthService/UpdateUserProfile',
            shared_dot_proto_dot_auth__service__pb2.UpdateUserProfileRequest.SerializeToString,
            shared_dot_proto_dot_auth__service__pb2.UserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
