# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from shared.proto import pricing_service_pb2 as shared_dot_proto_dot_pricing__service__pb2


class PricingServiceStub(object):
    """Pricing Service Definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecommendPrice = channel.unary_unary(
                '/omnipricex.pricing.PricingService/RecommendPrice',
                request_serializer=shared_dot_proto_dot_pricing__service__pb2.PriceRecommendationRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_pricing__service__pb2.PriceRecommendationResponse.FromString,
                )
        self.BulkRecommendPrices = channel.unary_unary(
                '/omnipricex.pricing.PricingService/BulkRecommendPrices',
                request_serializer=shared_dot_proto_dot_pricing__service__pb2.BulkPriceRecommendationRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_pricing__service__pb2.BulkPriceRecommendationResponse.FromString,
                )
        self.CreatePricingRule = channel.unary_unary(
                '/omnipricex.pricing.PricingService/CreatePricingRule',
                request_serializer=shared_dot_proto_dot_pricing__service__pb2.CreatePricingRuleRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_pricing__service__pb2.PricingRuleResponse.FromString,
                )
        self.GetPricingRule = channel.unary_unary(
                '/omnipricex.pricing.PricingService/GetPricingRule',
                request_serializer=shared_dot_proto_dot_pricing__service__pb2.GetPricingRuleRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_pricing__service__pb2.PricingRuleResponse.FromString,
                )
        self.UpdatePricingRule = channel.unary_unary(
                '/omnipricex.pricing.PricingService/UpdatePricingRule',
                request_serializer=shared_dot_proto_dot_pricing__service__pb2.UpdatePricingRuleRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_pricing__service__pb2.PricingRuleResponse.FromString,
                )
        self.DeletePricingRule = channel.unary_unary(
                '/omnipricex.pricing.PricingService/DeletePricingRule',
                request_serializer=shared_dot_proto_dot_pricing__service__pb2.DeletePricingRuleRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.ListPricingRules = channel.unary_unary(
                '/omnipricex.pricing.PricingService/ListPricingRules',
                request_serializer=shared_dot_proto_dot_pricing__service__pb2.ListPricingRulesRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_pricing__service__pb2.ListPricingRulesResponse.FromString,
                )
        self.ExecutePricingRule = channel.unary_unary(
                '/omnipricex.pricing.PricingService/ExecutePricingRule',
                request_serializer=shared_dot_proto_dot_pricing__service__pb2.ExecutePricingRuleRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_pricing__service__pb2.ExecutePricingRuleResponse.FromString,
                )
        self.CreatePricingDecision = channel.unary_unary(
                '/omnipricex.pricing.PricingService/CreatePricingDecision',
                request_serializer=shared_dot_proto_dot_pricing__service__pb2.CreatePricingDecisionRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_pricing__service__pb2.PricingDecisionResponse.FromString,
                )
        self.ApprovePricingDecision = channel.unary_unary(
                '/omnipricex.pricing.PricingService/ApprovePricingDecision',
                request_serializer=shared_dot_proto_dot_pricing__service__pb2.ApprovePricingDecisionRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_pricing__service__pb2.PricingDecisionResponse.FromString,
                )
        self.RejectPricingDecision = channel.unary_unary(
                '/omnipricex.pricing.PricingService/RejectPricingDecision',
                request_serializer=shared_dot_proto_dot_pricing__service__pb2.RejectPricingDecisionRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_pricing__service__pb2.PricingDecisionResponse.FromString,
                )
        self.ListPricingDecisions = channel.unary_unary(
                '/omnipricex.pricing.PricingService/ListPricingDecisions',
                request_serializer=shared_dot_proto_dot_pricing__service__pb2.ListPricingDecisionsRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_pricing__service__pb2.ListPricingDecisionsResponse.FromString,
                )
        self.GetPriceHistory = channel.unary_unary(
                '/omnipricex.pricing.PricingService/GetPriceHistory',
                request_serializer=shared_dot_proto_dot_pricing__service__pb2.GetPriceHistoryRequest.SerializeToString,
                response_deserializer=shared_dot_proto_dot_pricing__service__pb2.GetPriceHistoryResponse.FromString,
                )
        self.RecordPriceChange = channel.unary_unary(
                '/omnipricex.pricing.PricingService/RecordPriceChange',
                request_serializer=shared_dot_proto_dot_pricing__service__pb2.RecordPriceChangeRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class PricingServiceServicer(object):
    """Pricing Service Definition
    """

    def RecommendPrice(self, request, context):
        """Price recommendations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BulkRecommendPrices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePricingRule(self, request, context):
        """Pricing rules
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPricingRule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePricingRule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePricingRule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPricingRules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecutePricingRule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePricingDecision(self, request, context):
        """Pricing decisions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApprovePricingDecision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RejectPricingDecision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPricingDecisions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPriceHistory(self, request, context):
        """Price history
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordPriceChange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PricingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecommendPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.RecommendPrice,
                    request_deserializer=shared_dot_proto_dot_pricing__service__pb2.PriceRecommendationRequest.FromString,
                    response_serializer=shared_dot_proto_dot_pricing__service__pb2.PriceRecommendationResponse.SerializeToString,
            ),
            'BulkRecommendPrices': grpc.unary_unary_rpc_method_handler(
                    servicer.BulkRecommendPrices,
                    request_deserializer=shared_dot_proto_dot_pricing__service__pb2.BulkPriceRecommendationRequest.FromString,
                    response_serializer=shared_dot_proto_dot_pricing__service__pb2.BulkPriceRecommendationResponse.SerializeToString,
            ),
            'CreatePricingRule': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePricingRule,
                    request_deserializer=shared_dot_proto_dot_pricing__service__pb2.CreatePricingRuleRequest.FromString,
                    response_serializer=shared_dot_proto_dot_pricing__service__pb2.PricingRuleResponse.SerializeToString,
            ),
            'GetPricingRule': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPricingRule,
                    request_deserializer=shared_dot_proto_dot_pricing__service__pb2.GetPricingRuleRequest.FromString,
                    response_serializer=shared_dot_proto_dot_pricing__service__pb2.PricingRuleResponse.SerializeToString,
            ),
            'UpdatePricingRule': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePricingRule,
                    request_deserializer=shared_dot_proto_dot_pricing__service__pb2.UpdatePricingRuleRequest.FromString,
                    response_serializer=shared_dot_proto_dot_pricing__service__pb2.PricingRuleResponse.SerializeToString,
            ),
            'DeletePricingRule': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePricingRule,
                    request_deserializer=shared_dot_proto_dot_pricing__service__pb2.DeletePricingRuleRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListPricingRules': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPricingRules,
                    request_deserializer=shared_dot_proto_dot_pricing__service__pb2.ListPricingRulesRequest.FromString,
                    response_serializer=shared_dot_proto_dot_pricing__service__pb2.ListPricingRulesResponse.SerializeToString,
            ),
            'ExecutePricingRule': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecutePricingRule,
                    request_deserializer=shared_dot_proto_dot_pricing__service__pb2.ExecutePricingRuleRequest.FromString,
                    response_serializer=shared_dot_proto_dot_pricing__service__pb2.ExecutePricingRuleResponse.SerializeToString,
            ),
            'CreatePricingDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePricingDecision,
                    request_deserializer=shared_dot_proto_dot_pricing__service__pb2.CreatePricingDecisionRequest.FromString,
                    response_serializer=shared_dot_proto_dot_pricing__service__pb2.PricingDecisionResponse.SerializeToString,
            ),
            'ApprovePricingDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.ApprovePricingDecision,
                    request_deserializer=shared_dot_proto_dot_pricing__service__pb2.ApprovePricingDecisionRequest.FromString,
                    response_serializer=shared_dot_proto_dot_pricing__service__pb2.PricingDecisionResponse.SerializeToString,
            ),
            'RejectPricingDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.RejectPricingDecision,
                    request_deserializer=shared_dot_proto_dot_pricing__service__pb2.RejectPricingDecisionRequest.FromString,
                    response_serializer=shared_dot_proto_dot_pricing__service__pb2.PricingDecisionResponse.SerializeToString,
            ),
            'ListPricingDecisions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPricingDecisions,
                    request_deserializer=shared_dot_proto_dot_pricing__service__pb2.ListPricingDecisionsRequest.FromString,
                    response_serializer=shared_dot_proto_dot_pricing__service__pb2.ListPricingDecisionsResponse.SerializeToString,
            ),
            'GetPriceHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPriceHistory,
                    request_deserializer=shared_dot_proto_dot_pricing__service__pb2.GetPriceHistoryRequest.FromString,
                    response_serializer=shared_dot_proto_dot_pricing__service__pb2.GetPriceHistoryResponse.SerializeToString,
            ),
            'RecordPriceChange': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordPriceChange,
                    request_deserializer=shared_dot_proto_dot_pricing__service__pb2.RecordPriceChangeRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'omnipricex.pricing.PricingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PricingService(object):
    """Pricing Service Definition
    """

    @staticmethod
    def RecommendPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/omnipricex.pricing.PricingService/RecommendPrice',
            shared_dot_proto_dot_pricing__service__pb2.PriceRecommendationRequest.SerializeToString,
            shared_dot_proto_dot_pricing__service__pb2.PriceRecommendationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BulkRecommendPrices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/omnipricex.pricing.PricingService/BulkRecommendPrices',
            shared_dot_proto_dot_pricing__service__pb2.BulkPriceRecommendationRequest.SerializeToString,
            shared_dot_proto_dot_pricing__service__pb2.BulkPriceRecommendationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreatePricingRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/omnipricex.pricing.PricingService/CreatePricingRule',
            shared_dot_proto_dot_pricing__service__pb2.CreatePricingRuleRequest.SerializeToString,
            shared_dot_proto_dot_pricing__service__pb2.PricingRuleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPricingRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/omnipricex.pricing.PricingService/GetPricingRule',
            shared_dot_proto_dot_pricing__service__pb2.GetPricingRuleRequest.SerializeToString,
            shared_dot_proto_dot_pricing__service__pb2.PricingRuleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdatePricingRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/omnipricex.pricing.PricingService/UpdatePricingRule',
            shared_dot_proto_dot_pricing__service__pb2.UpdatePricingRuleRequest.SerializeToString,
            shared_dot_proto_dot_pricing__service__pb2.PricingRuleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeletePricingRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/omnipricex.pricing.PricingService/DeletePricingRule',
            shared_dot_proto_dot_pricing__service__pb2.DeletePricingRuleRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListPricingRules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/omnipricex.pricing.PricingService/ListPricingRules',
            shared_dot_proto_dot_pricing__service__pb2.ListPricingRulesRequest.SerializeToString,
            shared_dot_proto_dot_pricing__service__pb2.ListPricingRulesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExecutePricingRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/omnipricex.pricing.PricingService/ExecutePricingRule',
            shared_dot_proto_dot_pricing__service__pb2.ExecutePricingRuleRequest.SerializeToString,
            shared_dot_proto_dot_pricing__service__pb2.ExecutePricingRuleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreatePricingDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/omnipricex.pricing.PricingService/CreatePricingDecision',
            shared_dot_proto_dot_pricing__service__pb2.CreatePricingDecisionRequest.SerializeToString,
            shared_dot_proto_dot_pricing__service__pb2.PricingDecisionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ApprovePricingDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/omnipricex.pricing.PricingService/ApprovePricingDecision',
            shared_dot_proto_dot_pricing__service__pb2.ApprovePricingDecisionRequest.SerializeToString,
            shared_dot_proto_dot_pricing__service__pb2.PricingDecisionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RejectPricingDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/omnipricex.pricing.PricingService/RejectPricingDecision',
            shared_dot_proto_dot_pricing__service__pb2.RejectPricingDecisionRequest.SerializeToString,
            shared_dot_proto_dot_pricing__service__pb2.PricingDecisionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListPricingDecisions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/omnipricex.pricing.PricingService/ListPricingDecisions',
            shared_dot_proto_dot_pricing__service__pb2.ListPricingDecisionsRequest.SerializeToString,
            shared_dot_proto_dot_pricing__service__pb2.ListPricingDecisionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPriceHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/omnipricex.pricing.PricingService/GetPriceHistory',
            shared_dot_proto_dot_pricing__service__pb2.GetPriceHistoryRequest.SerializeToString,
            shared_dot_proto_dot_pricing__service__pb2.GetPriceHistoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RecordPriceChange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/omnipricex.pricing.PricingService/RecordPriceChange',
            shared_dot_proto_dot_pricing__service__pb2.RecordPriceChangeRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
