global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:8001']
    metrics_path: '/metrics'

  - job_name: 'pricing-service'
    static_configs:
      - targets: ['pricing-service:8002']
    metrics_path: '/metrics'

  - job_name: 'scraper-service'
    static_configs:
      - targets: ['scraper-service:8003']
    metrics_path: '/metrics'

  - job_name: 'competitor-service'
    static_configs:
      - targets: ['competitor-service:8004']
    metrics_path: '/metrics'

  - job_name: 'analytics-service'
    static_configs:
      - targets: ['analytics-service:8005']
    metrics_path: '/metrics'

  - job_name: 'llm-assistant-service'
    static_configs:
      - targets: ['llm-assistant-service:8006']
    metrics_path: '/metrics'
